# CI Build number is incremental and not related to actual version number of the product
version: '{build}'

init:
  - git config --global core.autocrlf true

install:
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - ps: dnvm install 1.0.0-rc2-16595 -r clr -a x86 -u
  - ps: dnvm list

nuget:
  disable_publish_on_pr: true

configuration: Release

before_build:
  - ps: dnu restore

test: off

artifacts:
  - path: artifacts\bin\**\$(configuration)\*.nupkg
    name: NugetPackage